### ISSUE TITLE
aws: cannot delete a filter policy for a subscription

### ISSUE THREAD

**Issue by dmacthedestroyer** [infobloxopen/atlas-pubsub#12]
Running the following code will create a subscription with a filter policy:
```
s := aws.NewSubscriber(config, "topic", "subID")
s.Start(ctx, map[string]string{"foo":"bar})
```
Then later, running the following code without a filter policy:
```
s.Start(ctx, nil)
```
**Expected Behavior**
It's expected that the filter policy is deleted and the subscription is now receiving all messages.

**Observed Behavior**
The original filter policy is still in place and the subscription is still filtering messages.

**Comment by dmacthedestroyer** [comment]
This is because of a shortcoming with the AWS API not allowing a filter to be cleared out for a subscription.

The solution is to delete and then recreate the subscription, which has a dangerous side-effect of data loss in the brief period in which the operation is taking place. Since this isn't expected to be a common scenario in production environments, it may be a tolerable risk.

**Comment by johnbelamaric** [comment]
Can't you create a new subscription and then delete the old one?

**Comment by dmacthedestroyer** [comment]
hmm... didn't think of that! I'll definitely try that first. I'm not sure if there are any kind of uniqueness constraints against that for a given topic,queue but it's definitely the best approach. 

Thanks!
